"use client";

import { useEffect, useState } from "react";
import { Activity, Boxes, CheckCircle2, ChevronRight, CircleUserRound, ClipboardCheck, Code2, Database, Fingerprint, LayoutDashboard, LoaderCircle, LogOut, Plus, Radar, Search, ShieldCheck, WalletCards } from "lucide-react";
import type { RegistryAgent, RegistryResponse } from "@/lib/registry";
import { connectArkivWallet, registerAgentCard } from "@/lib/wallet";

type View = "overview" | "registry" | "verify" | "claim";
const emptyRegistry: RegistryResponse = { status: "ready", agents: [], query: 'type="agent_card" AND protocol="mcp"', source: "arkiv", chainId: 60138453102 };

function Brand() { return <a className="brand focus-ring" href="#"><span className="brand-mark"><span /></span><b>CARDINAL</b></a>; }
function Chip({ children, good = false }: { children: React.ReactNode; good?: boolean }) { return <span className={`chip ${good ? "good" : ""}`}>{children}</span>; }

export function CardinalApp() {
  const [view, setView] = useState<View>("overview");
  const [registry, setRegistry] = useState<RegistryResponse>(emptyRegistry);
  const [wallet, setWallet] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [action, setAction] = useState("");
  const [message, setMessage] = useState("");

  async function refresh() {
    setLoading(true);
    try { setRegistry(await fetch(`/api/agents?search=${encodeURIComponent(search)}`).then((response) => response.json())); }
    catch { setRegistry({ ...emptyRegistry, status: "error", message: "Braga RPC could not be reached." }); }
    finally { setLoading(false); }
  }
  useEffect(() => {
    let active = true;
    fetch("/api/agents")
      .then((response) => response.json())
      .then((data) => { if (active) setRegistry(data); })
      .catch(() => { if (active) setRegistry({ ...emptyRegistry, status: "error", message: "Braga RPC could not be reached." }); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);

  async function connect() {
    setAction("connect"); setMessage("");
    try { setWallet(await connectArkivWallet()); setMessage("Wallet connected to Braga."); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Wallet connection failed."); }
    finally { setAction(""); }
  }

  const nav = (next: View) => { setView(next); setMessage(""); };
  return <div className="dashboard">
    <aside className="sidebar"><Brand /><div className="workspace-label">WORKSPACE</div><nav className="side-nav" aria-label="Dashboard navigation">
      <NavButton icon={<LayoutDashboard />} active={view === "overview"} onClick={() => nav("overview")}>Overview</NavButton>
      <NavButton icon={<Boxes />} active={view === "registry"} onClick={() => nav("registry")}>Registry <span>{registry.agents.length || ""}</span></NavButton>
      <NavButton icon={<ShieldCheck />} active={view === "verify"} onClick={() => nav("verify")}>Verify</NavButton>
      <NavButton icon={<Plus />} active={view === "claim"} onClick={() => nav("claim")}>Claim an agent</NavButton>
    </nav><div className="side-bottom"><div className="chain-state"><span className="live-dot" /> Braga testnet <span className="chain-id">{registry.chainId}</span></div>{wallet ? <div className="wallet-row"><CircleUserRound size={18} /><span><b>{wallet.slice(0, 6)}...{wallet.slice(-4)}</b><small>Connected wallet</small></span><button className="icon-button" onClick={() => setWallet(null)} aria-label="Disconnect wallet"><LogOut size={16} /></button></div> : <button className="button button-primary wallet-button" onClick={connect}>{action === "connect" ? <LoaderCircle className="spin" size={16} /> : <WalletCards size={16} />} Connect wallet</button>}</div></aside>
    <main className="main-panel"><header className="main-header"><div><span className="eyebrow">CARDINAL / {view.toUpperCase()}</span><h1>{view === "overview" ? "Registry overview" : view === "registry" ? "Verified agents" : view === "verify" ? "Verify evidence" : "Claim an agent"}</h1></div><div className="header-actions"><button className="button button-secondary" onClick={() => void refresh()}><Activity size={16} /> Refresh</button>{!wallet && <button className="button button-primary" onClick={connect}><WalletCards size={16} /> Connect</button>}</div></header>{message && <div className="notice"><CheckCircle2 size={16} /> {message}</div>}{view === "overview" && <Overview registry={registry} onNavigate={nav} loading={loading} />}{view === "registry" && <Registry registry={registry} search={search} setSearch={setSearch} loading={loading} />}{view === "verify" && <Verify />}{view === "claim" && <Claim wallet={wallet} onConnect={connect} onDone={(text) => { setMessage(text); void refresh(); }} />}</main>
  </div>;
}

function NavButton({ icon, active, children, onClick }: { icon: React.ReactNode; active: boolean; children: React.ReactNode; onClick: () => void }) { return <button className={`side-link ${active ? "active" : ""}`} onClick={onClick}>{icon}<span>{children}</span><ChevronRight size={14} /></button>; }
function Overview({ registry, onNavigate, loading }: { registry: RegistryResponse; onNavigate: (view: View) => void; loading: boolean }) { return <div className="view"><div className="overview-banner"><div><Chip good><span className="live-dot" /> Direct Braga RPC</Chip><h2>Evidence, before discovery.</h2><p>Cardinal only shows an agent when Arkiv returns a live card, a scanner verdict, and a recent prober attestation.</p></div><div className="banner-mark"><Fingerprint size={48} /></div></div><div className="stat-grid"><Stat label="Verified agents" value={loading ? "..." : String(registry.agents.length)} note="Live curated view" icon={<Boxes />} /><Stat label="Evidence signals" value={registry.agents.length ? "3 / 3" : "-"} note="Required per listing" icon={<ClipboardCheck />} /><Stat label="Chain" value="Braga" note={String(registry.chainId)} icon={<Database />} /></div><div className="split-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">RECENTLY VERIFIED</span><h3>Fresh attestations</h3></div><button className="text-button" onClick={() => onNavigate("registry")}>View registry <ChevronRight size={15} /></button></div>{registry.agents.slice(0, 4).map((agent) => <AgentRow key={agent.entityKey} agent={agent} />)}{!registry.agents.length && <Empty icon={<Radar />} title="No verified agents yet" text="The view is empty until real Arkiv entities satisfy the policy." />}</section><section className="panel policy-panel"><div className="panel-heading"><div><span className="eyebrow">ADMISSION POLICY</span><h3>Three signals</h3></div></div><PolicyRow icon={<Fingerprint />} title="Agent card" text="Unexpired operator or crawler entity" /><PolicyRow icon={<ShieldCheck />} title="Scan verdict" text="Pass from the published scanner wallet" /><PolicyRow icon={<Radar />} title="Attestation" text="Recent pass from a recognized prober" /></section></div></div>; }
function Stat({ label, value, note, icon }: { label: string; value: string; note: string; icon: React.ReactNode }) { return <div className="stat panel"><span className="stat-icon">{icon}</span><span className="eyebrow">{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function PolicyRow({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="policy-row"><span className="mini-icon">{icon}</span><span><b>{title}</b><small>{text}</small></span><CheckCircle2 size={16} className="check" /></div>; }
function AgentRow({ agent }: { agent: RegistryAgent }) { return <div className="agent-row"><span className="agent-symbol"><Code2 size={17} /></span><span><b>{agent.name}</b><small>{agent.endpoint}</small></span><Chip good>{agent.attestation.result}</Chip><span className="row-arrow"><ChevronRight size={17} /></span></div>; }
function Empty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="empty"><span>{icon}</span><b>{title}</b><small>{text}</small></div>; }

function Registry({ registry, search, setSearch, loading }: { registry: RegistryResponse; search: string; setSearch: (value: string) => void; loading: boolean }) { return <div className="view"><div className="toolbar"><div className="search-field"><Search size={16} /><label className="sr-only" htmlFor="agent-search">Search</label><input id="agent-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search agents or endpoints" /></div><Chip>{registry.agents.length} verified</Chip></div><section className="panel registry-panel"><div className="registry-source"><span><Database size={15} /> Direct source: {registry.source === "arkiv" ? "Braga RPC" : "Unavailable"}</span><code>{registry.query}</code></div>{loading ? <Empty icon={<LoaderCircle className="spin" />} title="Reading Arkiv" text="Querying live entities and joining their evidence." /> : registry.agents.length ? <div className="table-wrap"><table><thead><tr><th>Agent</th><th>Evidence</th><th>Class</th><th>Last checked</th><th>Latency</th></tr></thead><tbody>{registry.agents.map((agent) => <tr key={agent.entityKey}><td><b>{agent.name}</b><small>{agent.endpoint}</small></td><td><Chip good>scan pass</Chip> <Chip good>{agent.attestation.result}</Chip></td><td><Chip>{agent.class}</Chip></td><td>{agent.attestation.checkedAt ? new Date(agent.attestation.checkedAt * 1000).toLocaleString() : "-"}</td><td>{agent.attestation.latencyMs ? `${agent.attestation.latencyMs} ms` : "-"}</td></tr>)}</tbody></table></div> : <Empty icon={<Database />} title={registry.status === "error" ? "Braga RPC unavailable" : "No verified agents"} text={registry.message ?? "No live Arkiv entities satisfy the Cardinal admission policy."} />}</section></div>; }

function Verify() { const [mode, setMode] = useState<"scan" | "probe">("scan"); const [value, setValue] = useState(""); const [result, setResult] = useState<unknown>(null); const [running, setRunning] = useState(false); async function submit(event: React.FormEvent) { event.preventDefault(); setRunning(true); setResult(null); const response = await fetch(mode === "scan" ? "/api/scan" : "/api/probe", { method: "POST", headers: { "content-type": "application/json" }, body: mode === "scan" ? value : JSON.stringify({ endpoint: value }) }); setResult(await response.json()); setRunning(false); } return <div className="view"><div className="verify-grid"><form className="panel verify-form" onSubmit={submit}><div className="segmented"><button type="button" data-active={mode === "scan"} onClick={() => { setMode("scan"); setResult(null); }}>Scan JSON</button><button type="button" data-active={mode === "probe"} onClick={() => { setMode("probe"); setResult(null); }}>Probe URL</button></div><label htmlFor="verify-input">{mode === "scan" ? "Agent Card JSON" : "Public MCP endpoint"}</label>{mode === "scan" ? <textarea id="verify-input" value={value} onChange={(event) => setValue(event.target.value)} placeholder={'{"name":"...","endpoint":"https://..."}'} required /> : <input id="verify-input" type="url" value={value} onChange={(event) => setValue(event.target.value)} placeholder="https://agent.example.com/mcp" required />}<button className="button button-primary" disabled={running}>{running ? <LoaderCircle className="spin" size={16} /> : <ShieldCheck size={16} />} Run verification</button></form><section className="panel result-panel"><div className="panel-heading"><div><span className="eyebrow">UNMODIFIED RESPONSE</span><h3>Evidence result</h3></div></div>{result ? <pre>{JSON.stringify(result, null, 2)}</pre> : <Empty icon={<Code2 />} title="Nothing verified" text="The result from your next real operation will appear here." />}</section></div></div>; }

function Claim({ wallet, onConnect, onDone }: { wallet: string | null; onConnect: () => void; onDone: (text: string) => void }) { const [name, setName] = useState(""); const [endpoint, setEndpoint] = useState(""); const [caps, setCaps] = useState("tools"); const [running, setRunning] = useState(false); async function submit(event: React.FormEvent) { event.preventDefault(); if (!wallet) return onConnect(); setRunning(true); try { const result = await registerAgentCard(wallet as `0x${string}`, { name, endpoint, capabilities: caps.split(",").map((item) => item.trim()).filter(Boolean) }); onDone(`Card written to Braga. Entity ${result.entityKey.slice(0, 10)}...`); } catch (error) { onDone(error instanceof Error ? error.message : "Card write failed."); } finally { setRunning(false); } } return <div className="view"><div className="claim-grid"><section><span className="eyebrow">OPERATOR FLOW</span><h2>Put your agent on the record.</h2><p className="lead">Connect the wallet that owns the deployment, then publish a 24-hour claimed card directly to Braga.</p><div className="claim-steps"><PolicyRow icon={<WalletCards />} title="Connect wallet" text="Switches to Braga testnet" /><PolicyRow icon={<ClipboardCheck />} title="Publish card" text="Signs an operator-owned entity" /><PolicyRow icon={<Activity />} title="Stay alive" text="Heartbeat extends the entity" /></div></section><form className="panel claim-form" onSubmit={submit}><div className="form-heading"><span className="mini-icon"><Plus /></span><div><h3>Register MCP agent</h3><small>{wallet ? `Owner ${wallet.slice(0, 8)}...` : "Wallet required to sign"}</small></div></div><label htmlFor="agent-name">Agent name</label><input id="agent-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="My MCP server" required /><label htmlFor="agent-endpoint">MCP endpoint</label><input id="agent-endpoint" type="url" value={endpoint} onChange={(event) => setEndpoint(event.target.value)} placeholder="https://example.com/mcp" required /><label htmlFor="agent-caps">Capabilities</label><input id="agent-caps" value={caps} onChange={(event) => setCaps(event.target.value)} placeholder="tools, resources" /><button className="button button-primary" disabled={running}>{running ? <LoaderCircle className="spin" size={16} /> : <WalletCards size={16} />} {wallet ? "Sign and publish" : "Connect wallet"}</button><small className="form-note">This writes a real entity. There is no local demo registry.</small></form></div></div>; }
